apiVersion: apps/v1
kind: Deployment
metadata:
    name: kitchen-deployment
    labels:
        app: hotelup
    namespace: hotelup
spec:
    replicas: 1
    selector:
        matchLabels:
            app: kitchen
    template:
        metadata:
            name: kitchen
            labels:
                app: kitchen
        spec:
            containers:
              - name: kitchen
                image: wiaz/hotelup.kitchen:latest
                imagePullPolicy: Always
                env:
                  - name: ASPNETCORE_ENVIRONMENT
                    value: Production
                ports:
                  - containerPort: 8080
                    protocol: TCP
            restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
    name: kitchen-service
    labels:
        app: kitchen
    namespace: hotelup
spec:
    selector:
        app: kitchen
    ports:
      - protocol: TCP
        port: 5006
        targetPort: 8080
    type: ClusterIP
