name: Tests

on:
    pull_request:
        branches: [ "main" ]
    push:
        branches: [ "main" ]

jobs:
    build:
        
        runs-on: ubuntu-latest
        
        steps:
            -   uses: actions/checkout@v4
            -   name: Setup .NET
                uses: actions/setup-dotnet@v4
                with:
                    dotnet-version: 8.0.x
            -   name: Configure AWS credentials
                uses: aws-actions/configure-aws-credentials@v2
                with:
                    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    aws-region: us-east-1
            -   name: Restore dependencies
                run: dotnet restore
            -   name: Build
                run: dotnet build --no-restore
            -   name: Unit tests
                run: dotnet test Tests/HotelUp.Kitchen.Tests.Unit --no-build --verbosity normal
            -   name: Integration tests
                run: dotnet test Tests/HotelUp.Kitchen.Tests.Integration --no-build --verbosity normal
